
# Лабораторна робота 1 — Варіант 18  
**Тема:** Вступ до машинного навчання. Елементи лінійної алгебри.  


In [ ]:

import numpy as np
import math
from math import factorial
np.set_printoptions(precision=4, suppress=True)

def geometric_mean(arr):
    arr = np.array(arr, dtype=float).ravel()
    if np.any(arr <= 0):
        arr = np.where(arr<=0, 1e-12, arr)
    return float(np.exp(np.mean(np.log(arr))))


### Завдання 1 
**Формулювання:** Створіть одновимірний масив (вектор) з числами, які є кубами натуральних чисел, починаючи з 1, та виведіть його значення.

In [2]:

# Завдання 1.18 — куби натуральних чисел (наприклад, перші 10)
n = 10
cubes = np.array([i**3 for i in range(1, n+1)])
cubes


array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

### Завдання 2
**Формулювання:** Створіть матрицю 3x3, заповнену значеннями факторіалів перших натуральних чисел, та виведіть її значення.

In [3]:

# Завдання 2.18 — матриця 3x3 з факторіалами перших 9 натуральних чисел
vals = np.array([math.factorial(i) for i in range(1, 10)])
mat_2_18 = vals.reshape(3,3)
mat_2_18


array([[     1,      2,      6],
       [    24,    120,    720],
       [  5040,  40320, 362880]])

### Завдання 3
**Формулювання:** Створіть масив 3x3 з випадковими цілими числами від -5 до 5 та знайдіть суму модулів кожного рядка.

In [4]:

# Завдання 3.18 — сума модулів по кожному рядку
rng = np.random.default_rng(18)
A = rng.integers(-5, 6, size=(3,3))
row_abs_sums = np.sum(np.abs(A), axis=1)
A, row_abs_sums


(array([[ 4, -1, -3],
        [ 2,  4, -2],
        [-1, -5,  5]], dtype=int64),
 array([ 8,  8, 11], dtype=int64))

### Завдання 4
**Формулювання:** Створіть масив 3x3 з випадковими дійсними числами в [0,1] та знайдіть середнє геометричне всіх елементів.

In [5]:

# Завдання 4.18 — геометричне середнє елементів матриці
rng = np.random.default_rng(418)
M = rng.random((3,3))
gmean = geometric_mean(M)
M, gmean


(array([[0.3192, 0.9897, 0.2241],
        [0.2963, 0.9129, 0.8961],
        [0.7215, 0.9401, 0.0576]]),
 0.4439800050679794)

### Завдання 5
**Формулювання:** Створіть два одномірні масиви розміром 5 із випадковими дійсними числами в [0,1] та виконайте поелементні +, −, ×.

In [6]:

# Завдання 5.18 — поелементні операції
rng = np.random.default_rng(518)
a = rng.random(5)
b = rng.random(5)
add_ab = a + b
sub_ab = a - b
mul_ab = a * b
a, b, add_ab, sub_ab, mul_ab


(array([0.2156, 0.9245, 0.4426, 0.7462, 0.2934]),
 array([0.2572, 0.8751, 0.5002, 0.9325, 0.8333]),
 array([0.4729, 1.7996, 0.9427, 1.6788, 1.1267]),
 array([-0.0416,  0.0494, -0.0576, -0.1863, -0.5398]),
 array([0.0555, 0.809 , 0.2214, 0.6959, 0.2445]))

### Завдання 6
**Формулювання:** Створіть дві матриці 3x3 з випадковими цілими числами в діапазоні [1,5] та знайдіть їх добуток.

In [7]:

# Завдання 6.18 — добуток двох матриць 3x3
rng = np.random.default_rng(618)
X = rng.integers(1,6,size=(3,3))
Y = rng.integers(1,6,size=(3,3))
prod_XY = X @ Y
X, Y, prod_XY


(array([[1, 3, 4],
        [4, 1, 2],
        [5, 3, 3]], dtype=int64),
 array([[5, 4, 3],
        [5, 1, 5],
        [1, 1, 2]], dtype=int64),
 array([[24, 11, 26],
        [27, 19, 21],
        [43, 26, 36]], dtype=int64))

### Завдання 7
**Формулювання:** Створіть матриці 2x3 та 3x2 (цілі [1,5]) та перемножте їх.

In [8]:

# Завдання 7.18 — 2x3 @ 3x2
rng = np.random.default_rng(718)
A = rng.integers(1,6,size=(2,3))
B = rng.integers(1,6,size=(3,2))
C = A @ B
A, B, C


(array([[4, 5, 3],
        [3, 5, 3]], dtype=int64),
 array([[3, 5],
        [5, 3],
        [4, 2]], dtype=int64),
 array([[49, 41],
        [46, 36]], dtype=int64))

### Завдання 8
**Формулювання:** Створіть матрицю 3x3 з випадкових цілих [1,15] та знайдіть її обернену (перегенеруйте, якщо невиродна не вийшла).

In [9]:

# Завдання 8.18 — обернена матриця 3x3
rng = np.random.default_rng(818)
while True:
    M = rng.integers(1,16,size=(3,3))
    det = np.linalg.det(M)
    if abs(det) > 1e-8:
        Minv = np.linalg.inv(M)
        break
M, det, Minv


(array([[10,  1,  4],
        [ 3,  1,  4],
        [ 4, 13,  1]], dtype=int64),
 -356.9999999999999,
 array([[ 0.1429, -0.1429, -0.    ],
        [-0.0364,  0.0168,  0.0784],
        [-0.098 ,  0.3529, -0.0196]]))

### Завдання 9
**Формулювання:** Створіть матрицю 4x4 з випадкових дійсних чисел у [0,10] та транспонуйте її.

In [10]:

# Завдання 9.18 — транспонування 4x4
rng = np.random.default_rng(918)
M = rng.random((4,4)) * 10.0
MT = M.T
M, MT


(array([[2.6179, 0.4213, 7.8814, 5.0124],
        [2.3537, 9.0605, 5.4505, 3.0631],
        [8.3003, 6.8211, 8.7112, 3.8267],
        [0.8565, 1.3929, 2.9078, 2.695 ]]),
 array([[2.6179, 2.3537, 8.3003, 0.8565],
        [0.4213, 9.0605, 6.8211, 1.3929],
        [7.8814, 5.4505, 8.7112, 2.9078],
        [5.0124, 3.0631, 3.8267, 2.695 ]]))

### Завдання 10
**Формулювання:** Матриця 3x4 та вектор 4x1, обидва з дійсних чисел у [0,1]; знайти добуток.

In [11]:

# Завдання 10.18 — M(3x4) @ v(4x1)
rng = np.random.default_rng(1018)
M = rng.random((3,4))
v = rng.random((4,1))
Mv = M @ v
M, v, Mv


(array([[0.594 , 0.455 , 0.8715, 0.8144],
        [0.5282, 0.6765, 0.2891, 0.5992],
        [0.4847, 0.6512, 0.8041, 0.675 ]]),
 array([[0.0826],
        [0.6563],
        [0.3229],
        [0.363 ]]),
 array([[0.9247],
        [0.7985],
        [0.9721]]))

### Завдання 11
**Формулювання:** Матриця 2x3 та вектор 3x1, обидва з дійсних чисел у [0,1]; знайти добуток.

In [12]:

# Завдання 11.18 — A(2x3) @ x(3x1)
rng = np.random.default_rng(1118)
A = rng.random((2,3))
x = rng.random((3,1))
Ax = A @ x
A, x, Ax


(array([[0.3785, 0.8603, 0.0093],
        [0.0095, 0.1241, 0.5976]]),
 array([[0.6684],
        [0.0659],
        [0.72  ]]),
 array([[0.3163],
        [0.4448]]))

### Завдання 12
**Формулювання:** Дві матриці 3x3 (цілі [1,10]); знайти суму елементів головної діагоналі кожної (окремо).

In [13]:

# Завдання 12.18 — сума головної діагоналі для двох матриць
rng = np.random.default_rng(1218)
A = rng.integers(1,11,size=(3,3))
B = rng.integers(1,11,size=(3,3))
trace_A = np.trace(A)
trace_B = np.trace(B)
A, B, trace_A, trace_B


(array([[4, 6, 2],
        [4, 2, 6],
        [9, 6, 8]], dtype=int64),
 array([[ 5, 10,  8],
        [ 9,  7,  3],
        [ 3,  5,  8]], dtype=int64),
 14,
 20)

### Завдання 13
**Формулювання:** Дві матриці 2x2 з цілими у діапазоні [-5,5]; знайти добуток усіх елементів кожної матриці.

In [14]:

# Завдання 13.18 — добуток елементів у 2x2
rng = np.random.default_rng(1318)
A = rng.integers(-5,6,size=(2,2))
B = rng.integers(-5,6,size=(2,2))
prod_A = int(np.prod(A))
prod_B = int(np.prod(B))
A, B, prod_A, prod_B


(array([[-3,  5],
        [ 0,  0]], dtype=int64),
 array([[ 0,  0],
        [-3,  2]], dtype=int64),
 0,
 0)

### Завдання 14
**Формулювання:** Створіть матрицю 3x3 (цілі [1,10]) та знайдіть найбільший елемент.

In [15]:

# Завдання 14.18 — найбільший елемент
rng = np.random.default_rng(1418)
M = rng.integers(1,11,size=(3,3))
max_elem = int(np.max(M))
M, max_elem


(array([[ 6,  6,  5],
        [ 5,  8,  1],
        [10, 10,  1]], dtype=int64),
 10)

### Завдання 15
**Формулювання:** Матриця 4x4 (дійсні в [-1,1]); вектор-стовпчик із кількістю від’ємних елементів по кожному рядку.

In [16]:

# Завдання 15.18 — кількість від'ємних елементів у рядках
rng = np.random.default_rng(1518)
M = rng.uniform(-1,1,size=(4,4))
neg_counts = np.sum(M < 0, axis=1).reshape(-1,1)
M, neg_counts


(array([[-0.3526,  0.155 , -0.1935, -0.6931],
        [-0.2872,  0.4253,  0.7482, -0.9081],
        [ 0.8668, -0.1754, -0.2744, -0.4907],
        [ 0.4341,  0.3784,  0.2925, -0.1126]]),
 array([[3],
        [2],
        [3],
        [1]]))