In [1]:
import numpy as np

In [5]:
import numpy as np

# Завдання 1.
# Умова:
# "Задати вектор, що складається з перших п’яти натуральних чисел."

vector = np.array([1, 2, 3, 4, 5])

vector

array([1, 2, 3, 4, 5])

In [4]:
# Завдання 2.
# Умова:
# "Транспонувати вектор."

v1 = np.matrix([1, 2, 3, 4, 5])

print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [6]:
# Завдання 3.
# Умова:
# "Напишіть функцію, яка перевертає вектор у зворотному порядку."

v = np.array([1, 2, 3, 4, 5])

print(v[::-1])

[5 4 3 2 1]


In [7]:
# Завдання 4.
# Умова:
# "Обчислити середнє значення вектора."

print(np.mean(v))

3.0


In [8]:
# Завдання 5.
# Умова:
# "Знайти найбільший і найменший елементи вектора."

print(np.max(v))
print(np.min(v))

5
1


In [9]:
# Завдання 6.
# Умова:
# "Обчислити скалярний добуток (dot product) двох векторів."

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1 * v2)

32
[ 4 10 18]


In [10]:
# Завдання 7.
# Умова:
# "Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини)."

v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)

v / norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [11]:
# Завдання 8.
# Умова:
# "Задайте два вектори. Визначте, чи є вони ортогональними.
#  Підказка: якщо скалярний добуток дорівнює нулю, вектори ортогональні."

v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

In [12]:
import numpy as np

# Завдання 9.
# Умова:
# "Визначити унікальні елементи вектора."

v = np.array([1, 2, 3, 2, 4, 5, 3])

np.unique(v)

array([1, 2, 3, 4, 5])

In [13]:
# Завдання 10.
# Умова:
# "Знайти вектори."

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


In [14]:
# Завдання 11.
# Умова:
# "Перевірити, чи дорівнює довжина вектора 5."

vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)

np.isclose(length, 5)

np.False_

In [15]:
# Завдання 12.
# Умова:
# "Задати матрицю, заповнену випадковими числами."

a = np.random.randint(0, 11, (3, 3))

a

array([[2, 2, 1],
       [6, 8, 2],
       [2, 8, 6]])

In [16]:
# Завдання 13.
# Умова:
# "Обчислити визначник матриці."

np.linalg.det(a)

np.float64(31.999999999999986)

In [17]:
# Завдання 14.
# Умова:
# "Знаходження оберненої матриці."

np.linalg.inv(a)

array([[ 1.    , -0.125 , -0.125 ],
       [-1.    ,  0.3125,  0.0625],
       [ 1.    , -0.375 ,  0.125 ]])

In [18]:
# Завдання 15.
# Умова:
# "Розв’яжіть систему лінійних рівнянь A·x=b, де A – матриця коефіцієнтів,
#  b – вектор вільних членів."

a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


In [19]:
# Завдання 16.
# Умова:
# "Множення двох матриць."

a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

np.dot(a, b)

array([-2, -6, 16])

In [20]:
# Завдання 17.
# Умова:
# "Транспонування матриці."

print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [21]:
# Завдання 18.
# Умова:
# "Перевірка симетричності матриці."

matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])

np.allclose(matrix, matrix.T)

True

In [22]:
# Завдання 19.
# Умова:
# "Обчислення сліду матриці."

np.trace(matrix)

np.int64(6)

In [23]:
# Завдання 20.
# Умова:
# "Дії з матрицями."

a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
# Завдання 21.
# Умова:
# "Піднесення матриці до ступеня."

a = np.matrix([[1, 2], [3, 4]])

np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

In [25]:
# Завдання 22.
# Умова:
# "Сортування рядків або стовпців матриці."

b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [27]:
# Завдання 23.
# Умова:
# "Підрахувати суму елементів кожного рядка матриці.
#  Відповідь запиши, як вектор-стовпчик."

row_sums = np.sum(a, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[3]
 [7]]
